"""recriando banco

Revision ID: fc79b18fe85f
Revises: 
Create Date: 2025-02-04 23:05:41.875299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc79b18fe85f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materia',
    sa.Column('id_materia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_materia')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('senha', sa.String(length=200), nullable=True),
    sa.Column('tipo_user', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assunto',
    sa.Column('id_assunto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('duracao', sa.Float(), nullable=True),
    sa.Column('id_materia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_materia'], ['materia.id_materia'], ),
    sa.PrimaryKeyConstraint('id_assunto')
    )
    op.create_table('formulario',
    sa.Column('id_formulario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('tempo_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_formulario')
    )
    op.create_table('conteudo',
    sa.Column('id_conteudo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=True),
    sa.Column('id_assunto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_assunto'], ['assunto.id_assunto'], ),
    sa.PrimaryKeyConstraint('id_conteudo')
    )
    op.create_table('peso',
    sa.Column('id_materia_peso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('id_formulario', sa.Integer(), nullable=True),
    sa.Column('id_materia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_formulario'], ['formulario.id_formulario'], ),
    sa.ForeignKeyConstraint(['id_materia'], ['materia.id_materia'], ),
    sa.PrimaryKeyConstraint('id_materia_peso')
    )
    op.create_table('progresso',
    sa.Column('id_progresso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concluido', sa.Integer(), nullable=True),
    sa.Column('tempo_estudado', sa.Float(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_assunto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_assunto'], ['assunto.id_assunto'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_progresso')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progresso')
    op.drop_table('peso')
    op.drop_table('conteudo')
    op.drop_table('formulario')
    op.drop_table('assunto')
    op.drop_table('usuario')
    op.drop_table('materia')
    # ### end Alembic commands ###
